### PR TITLE
Add fix to check if order still exists. Fix #169

### LINKED ISSUE #169: in takeOrder check if order still exists
related to https://github.com/melonproject/ipfs-frontend/issues/209

### PR DESCRIPTION
**Pull request by jennazenk**
### Changed
- Fix #169 : add a check for existing order

### CODE REVIEW

File: lib/fund/transactions/takeOrder.js [hunk 1]
```diff
@@ -26,93 +26,97 @@ const takeOrder = (
...
+      ensure(
+        owner.toLowerCase() === wallet.address.toLowerCase(),
+        'Not owner of fund',
+      );
+
+      const isInAssetList = fundContract.instance.isInAssetList.call({}, [
+        getAddress(order.sell.symbol),
+      ]);
+      {
+        /* const ownedAssets = await fundContract.instance.ownedAssets.call({}, []);
```
Comment (schmidsi) [inline lib/fund/transactions/takeOrder.js]: Why is this commented out?

Comment (jennazenk) [reply lib/fund/transactions/takeOrder.js]: pre flight call that was not passing on the protocol. Will try them again on next integration test
